
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./myproject:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env 
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=yourpassword
    env_file:
      - ./.env 
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    command: celery -A myproject worker -l info
    volumes:
      - ./myproject:/app
    env_file:
      - ./.env 
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: