# Generated by Django 5.0.5 on 2024-05-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='item_name',
        ),
    ]
