# Generated by Django 5.0.5 on 2024-05-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menucategory_remove_menu_cuisine_menu_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='myapp.menucategory'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='menu_category_name',
            field=models.CharField(max_length=200),
        ),
    ]
