# Generated by Django 5.0.5 on 2024-05-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_menu_category_name_menucategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='category',
            new_name='name',
        ),
    ]
