# Generated by Django 5.0.5 on 2024-05-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
