# Generated by Django 5.0.5 on 2024-05-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_menu_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
