# Generated by Django 5.0.6 on 2024-05-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_booking_myapp_booki_name_b4d8a2_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
    ]
