# Generated by Django 5.0.6 on 2024-05-17 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_category_id_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
